### ISSUE TITLE
README 수정

### ISSUE THREAD

**Issue by suhyeoonn** [yyujjin/outfit-picker-backend#2]
API 목록 확인이 어려워서 다른 템플릿 참고하여 변경되면 좋을 것 같아요!
👍  https://gist.github.com/azagniotov/a4b16faf0febd12efbc6c3d7370383a6
https://github.com/nodes-vapor/readme/blob/master/Documentation/how-to-write-apis.md#authentication
https://github.com/jamescooke/restapidocs/tree/master/examples

## 예시
------------------------------------------------------------------------------------------

#### Creating new/overwriting existing stubs & proxy configs

<details>
 <summary><code>POST</code> <code><b>/</b></code> <code>(overwrites all in-memory stub and/or proxy-config)</code></summary>

##### Parameters

> | name      |  type     | data type               | description                                                           |
> |-----------|-----------|-------------------------|-----------------------------------------------------------------------|
> | None      |  required | object (JSON or YAML)   | N/A  |

##### Responses

> | http code     | content-type                      | response                                                            |
> |---------------|-----------------------------------|---------------------------------------------------------------------|
> | `201`         | `text/plain;charset=UTF-8`        | `Configuration created successfully`                                |
> | `400`         | `application/json`                | `{"code":"400","message":"Bad Request"}`                            |
> | `405`         | `text/html;charset=utf-8`         | None                                                                |

##### Example cURL

> ```javascript
>  curl -X POST -H "Content-Type: application/json" --data @post.json http://localhost:8889/
> ```

</details>

**Comment by yyujjin** [comment]
열심히 했슴다. 확인 부탁드림다. 🫠
