### ISSUE TITLE
GET /api/coordis API 호출 시 데이터가 있음에도 에러가 발생하는 문제

### ISSUE THREAD

**Issue by suhyeoonn** [yyujjin/outfit-picker-backend#6]
`GetCoordiLogs`컨트롤러에서 `for rows.Next() {}` 가 끝난 후 `if !rows.Next() {}`를 체크하는데, 
셀렉트한 row를 다 coordiList 슬라이스에 넣은 상태면 rows.Next()는 false를 리턴하기에 에러가 무조건 발생할 것 같아요! 확인 부탁드리고,

README에는 리스폰스가 배열형태로 내려오는걸로 되어있는데, 실제 데이터는 data로 감싸져서 내려오고 있어요
- README
  -  `[{...}, {...}]`
- 실제 값
  - `{"data": [{...}, {...}]}`

README와 동일하게 맞추려면 아래처럼 수정하면 됩니닷
`c.IndentedJSON(http.StatusOK, coordiList)`

**Comment by yyujjin** [comment]
수정했쑴둥
